apiVersion: v1
kind: Service
metadata:
  name: nginx-metrics
  namespace: demo
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: metrics
      port: 9113
      targetPort: metrics
  type: ClusterIP
