apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - demo
  selector:
    matchLabels:
      app: nginx
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
