---
- name: Prepare Loki storage directory
  ansible.builtin.file:
    path: /var/lib/loki
    state: directory
    mode: "0777"
  become: true
  
- name: Install Loki
  ansible.builtin.import_tasks: loki.yml

- name: Install Fluentd
  ansible.builtin.import_tasks: fluentd.yml

- name: Configure Grafana Loki datasource
  ansible.builtin.import_tasks: grafana.yml
