[master]
mrrobot ansible_host=177.1.180.84 ansible_user=mrrobot

[workers]
mrworker1 ansible_host=177.1.180.202 ansible_user=mrworker1
mrworker2 ansible_host=177.1.180.215 ansible_user=mrworker2

[myVMs:children]
master
workers

[all:vars]
ansible_user=mrrobot
ansible_become=true
